# -*- coding: utf-8 -*-
"""Analyzing Factors Affecting Employee Salaries

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MXR68v-qupmmcTvW1J5Ix-GN9h585piC
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv('Salary Data.csv')

#Data Exploration
print("Dataset Overview:")
print(data.head())
print(data.info())

"""
Objective: Identifying how different factors such as education level, expereience, job title,
and industry affect salaries.  This analysis is useful for understanding salary trends
and disparities across various professions and demographics.
"""

# Data Cleaning
# Handle missing values
data = data.dropna(subset=['salary','experience','education_level'])

# Standarizing catagories
# Converting all salary values to common currency and adjusting education levels to standard categories.
data['education_level'] = data['education_level'].replace({
    'Bachelors':'Bachelor’s',
    'Masters':'Master’s',
    'phd':'PhD'
})

# Exploratory Data Analysis
# Salary Distribution

plt.figure(figsize=(10,6))
sns.histplot(data['salary'], kde = True)
plt.title('Salary Distribution')
plt.xlabel('Salary')
plt.ylabel('Frequency')
plt.show()

"""
The salary distribution shows most employees earn between $50,000 and $150,000,
with fewer high earners above $150,000.
The data is right-skewed, indicating that high salaries are less common.
"""

# Average Salary by Education Level
avg_salary_by_education = data.groupby('education_level')['salary'].mean()
plt.figure(figsize=(10,6))
avg_salary_by_education.plot(kind='bar',color='skyblue')
plt.title('Average Salary by Education Level')
plt.xlabel("Education Level")
plt.ylabel("Average Salary")
plt.show()

"""
This graph shows the average salary by education level. Employees with a PhD have the highest average salary,
followed by those with a Master's degree, while those with a Bachelor's degree
earn the lowest average salary. The chart highlights a positive
correlation between education level and salary.
"""

# Salary vs Years of Experience
plt.figure(figsize=(10,6))
sns.lineplot(x='experience',y='salary',data=data, marker='o',ci=None)
plt.title("Salary vs Years of Experience")
plt.xlabel("Years of Experience")
plt.ylabel("Salary")
plt.show()

"""
The chart shows that salary generally increases with years of experience, with substantial growth early on
with substantial growth early on, steady progress mid-career,
and potential for significant earnings with 20+ years of experience.
"""

# Average Salary by Job Title
avg_salary_by_job = data.groupby('Job Title')['salary'].mean().sort_values(ascending=False).head(10)
plt.figure(figsize=(10,6))
avg_salary_by_job.plot(kind='bar',color='purple')
plt.title("Top 10 Job Titles by Average Salary")
plt.xlabel("Job Title")
plt.ylabel("Average Salary")
plt.show()

"""
This chart ranks the top 10 job titles by average salary,
with CEO and Cheif Technology Officer earning the highest salaries over $250,000.
Other roles like VP of Finance and various Director positions,
range between $200,000 and $250,000.
"""